version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres:alpine
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    depends_on:
      - rabbitmq

networks:
  bridge:
    external: true
